version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: beehive-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: beehive
      MONGO_INITDB_ROOT_PASSWORD: beehive
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
